### ISSUE TITLE
not read the log records

### ISSUE THREAD

**Issue by izniburak** [uuf6429/httpdmon#16]
I installed but does not read the log records. why could it be? I'm doing what mistake?
server: ubuntu14.04

**Comment by uuf6429** [comment]
Hello,

In the last change, you also have to download the right definitions....see the readme.md for more.

**Comment by uuf6429** [comment]
Actually, you are right...something seems broke.

For now either wait for a fix or go back to an earlier version.

**Comment by izniburak** [comment]
i hope, the problem can be solved in a short time.

**Comment by izniburak** [comment]
Hi, I guess update made. but still not working.

**Comment by uuf6429** [comment]
Fixed in 9fd54159872deeef7acbc0957478b0bfdd8c23bf

**Comment by izniburak** [comment]
i tested again. i do everything, but still not working. it doesn't give any error message. i wonder where am i doing wrong? can you give an example?

**Comment by uuf6429** [comment]
Hmm, it is possible the current definitions do not cover the log files on your system.
Can you please tell me where the access and error logs are located?

**Comment by izniburak** [comment]
access and error logs are located in 
/var/log/apache2/access.log
/var/log/apache2/error.log

By the way, 
D=$NAME is D=linux.php ? true? I'm using in this way but does not run.

**Comment by uuf6429** [comment]
Since the last update, if no log definitions exist, an exception will be thrown.
Therefore, I assume that `linux.php` is installed correctly and picked up.
Are you sure that the log files you mentioned are actually being used? Do they change?
Also make sure that `httpdmon -v` says the version is '2.0.4'.

This is rather strange since I have a very similar setup and seems to work fine.

**Comment by izniburak** [comment]
problems arise from the apache2 log configuration. I solved now. Thank you :)

**Comment by uuf6429** [comment]
No worries, glad to hear this helped you solve a problem. :)
